local _M = {}

--- @param cs ColorScheme
_M.setup = function (cs)
  return {
    ColorColumn     = {},
    Conceal         = {},
    CurSearch       = {},
    Cursor          = {},
    lCursor         = {},
    CursorIM        = {},
    CursorColumn    = { link = "CursorLine" },
    CursorLine      = { bg = cs.editor.lineHighlightBackground },
    Directory       = {},
    DiffAdd         = {},
    DiffChange      = {},
    DiffDelete      = {},
    DiffText        = {},
    EndOfBuffer     = { fg = cs.editor.background },
    TermCursor      = {},
    TermCursorNC    = {},
    ErrorMsg        = { fg = cs.base.red },
    WinSeparator    = { fg = cs.base.gray },
    Folded          = {},
    FoldColumn      = {},
    SignColumn      = { bg = cs.editor.background },
    IncSearch       = {},
    Substitute      = {},
    LineNr          = { fg = cs.editor.lineNumber.fg },
    LineNrAbove     = { link = "LineNr" },
    LineNrBelow     = { link = "LineNr" },
    CursorLineNr    = { fg = cs.editor.lineNumber.activeFg, bold = true },
    CursorLineFold  = {},
    CursorLineSign  = {},
    MatchParen      = {},
    ModeMsg         = {},
    MsgArea         = {},
    MsgSeparator    = {},
    MoreMsg         = {},
    NonText         = { fg = cs.editor.background },
    Normal          = { bg = cs.editor.background },
    NormalFloat     = {},
    NormalNC        = { bg = cs.editor.background },
    Pmenu           = {},
    PmenuSel        = {},
    PmenuSbar       = {},
    PmenuThumb      = {},
    Question        = {},
    QuickFixLine    = {},
    Search          = {},
    SpecialKey      = {},
    SpellBad        = {},
    SpellCap        = {},
    SpellLocal      = {},
    SpellRare       = {},
    StatusLine      = { bg = cs.editor.background },
    StatusLineNC    = {},
    TabLine         = {},
    TabLineFill     = {},
    TabLineSel      = {},
    Title           = {},
    Visual          = { bg = cs.editor.selectionBackground },
    VisualNOS       = { link = "Visual" },
    WarningMsg      = {},
    Whitespace      = {},
    WildMenu        = {},
    WinBar          = {},
    WinBarNC        = {},
  }
end

return _M
